import GeneralTextTemplate from "@/components/organisms/general/GeneralTextTemplate";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cookies Disclaimer - Albania Gateway",
};

const disclaimerData = {
  mainTitle: "Disclaimer",
  sections: [
    {
      title: "General Information",
      para: "The information provided by Albania Gateway ('we,' 'us,' or 'our') on https://albaniagateway.com/ (the 'Site') is for general informational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.",
    },
    {
      title: "External Links Disclaimer",
      para: "The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.",
    },
    {
      title: "Content Disclaimer",
      para: "The Site may contain content (including but not limited to text, images, and videos) that is not original and has been sourced from the internet, including search engines like Google, or generated by AI technologies. While we strive to ensure that the content provided is accurate and up-to-date, we do not guarantee the authenticity or originality of such content. Any images or content not created by us are owned by their respective creators and are used under fair use principles. If you are the owner of any content and believe it has been used without proper credit or in violation of your copyright, please contact us immediately, and we will address your concerns promptly.",
    },
    {
      title: "No Professional Advice",
      para: "The Site cannot and does not contain professional travel advice. The travel information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of travel, legal, financial, or other advice. The use or reliance of any information contained on this site is solely at your own risk.",
    },
    {
      title: "Affiliate Disclosure",
      para: "The Site may contain links to affiliate websites, and we receive an affiliate commission for any purchases made by you on the affiliate website using such links.",
    },
    {
      title: "Fair Use Notice",
      para: "This site contains copyrighted material, the use of which has not always been specifically authorized by the copyright owner. We are making such material available for criticism, comment, news reporting, teaching, scholarship, or research. We believe this constitutes a 'fair use. If you wish to use copyrighted material from this site for purposes of your own that go beyond 'fair use,' you must obtain permission from the copyright owner.",
    },
    {
      title: "Contact Us",
      para: "If you have any questions or concerns regarding this disclaimer, please feel free to contact us at: Email: momotech.al@gmail.com so we can remove the content",
    },
  ],
};

export default function page() {
  return (
    <GeneralTextTemplate
      mainTitle={disclaimerData.mainTitle}
      sections={disclaimerData.sections}
    />
  );
}
